minamaxdjango/minamax/urls.py
from django.urls import path
from .views import signup
from . import views
from django.contrib.auth.views import LoginView
from .views import custom_login

app_name = "minamax"
urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("profile/", views.profile, name="profile"),
    path("login/", views.custom_login, name="login"),
    path("logout/", LoginView.as_view(), name="logout"),
    path("<int:event_id>/", views.detail, name="detail"),
    path("<int:event_id>/results/", views.results, name="results"),
    path("<int:possibility_id>/change_result/", views.change_result, name="change_result"),
    path("to_bet/", views.to_bet, name="to_bet"),
]

minamaxdjango/minamaxdjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("minamax/", include("minamax.urls")),
    path("admin/", admin.site.urls),
]

minamaxdjango/minamax/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    points = models.IntegerField(default=100)


class Event(models.Model):
    id = models.AutoField(primary_key=True)
    event_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    event_date = models.DateTimeField("date event")
    def __str__(self):
        return str(self.id) + " / " + self.event_text


class Possibility(models.Model):
    id = models.AutoField(primary_key=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    description_text = models.CharField(max_length=200)
    quotation = models.FloatField(default=2.0)
    RESULT_CHOICES = [("Pending", "Pending"), ("Win", "Win"), ("Lose", "Lose")]
    result = models.CharField(max_length=10, choices=RESULT_CHOICES, default="Pending")
    def __str__(self):
        return str(self.id) + " / " + self.event.event_text + " / " + self.description_text + " / " + str(self.quotation)


class Bet(models.Model):
    id = models.AutoField(primary_key=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    possibility = models.ForeignKey(Possibility, on_delete=models.CASCADE)
    putting = models.FloatField(default=0.0)
    username = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.id) + " / " + str(self.possibility.description_text) + " / " + self.username.username + " / " + str(self.putting)

minamaxdjango/minamax/forms.py
# forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from .models import CustomUser
from .models import Possibility
from .models import Bet


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ["username", "email", "password1", "password2"]


class PossibilityResultForm(forms.ModelForm):
    class Meta:
        model = Possibility
        fields = ['result']
        RESULT_CHOICES = [("Win", "Win"), ("Lose", "Lose")]
        result = forms.ChoiceField(choices=RESULT_CHOICES)

class CustomLoginForm(AuthenticationForm):
    pass


class BetForm(forms.ModelForm):
    class Meta:
        model = Bet
        fields = ["id", "event", "possibility", "putting"]

minamaxdjango/minamax/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import get_object_or_404, render
from django.http import Http404
from django.http import HttpResponse
from .models import Possibility
from .models import CustomUser
from .models import Event
from .models import Bet
from django.template import loader
from .forms import CustomUserCreationForm, BetForm
from .forms import CustomUserCreationForm
from .forms import PossibilityResultForm
from django.contrib.auth.views import LoginView


def index(request):
    latest_event_list = Event.objects.order_by("-pub_date")[:5]
    context = {"latest_event_list": latest_event_list}
    return render(request, "minamax/index.html", context)


def detail(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    possibilities_list = Possibility.objects.filter(event=event)
    context = {"possibilities_list": possibilities_list, "event": event}
    return render(request, "minamax/detail.html", context)


def results(request, event_id):
    response = "You're looking at the results of event %s."
    return HttpResponse(response % event_id)


def vote(request, event_id):
    return HttpResponse("You're voting on question %s." % event_id)


def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("minamax:index")
    else:
        form = CustomUserCreationForm()
    return render(request, "minamax/signup.html", {"form": form})


@login_required
def profile(request):
    user = get_object_or_404(CustomUser, pk=request.user.pk)
    return render(request, "minamax/profile.html", {"user": request.user})


def custom_login(request, *args, **kwargs):
    return LoginView.as_view(template_name='minamax/login.html')(request, *args, **kwargs)

@user_passes_test(lambda u: u.is_staff)
def change_result(request, possibility_id):
    possibility = get_object_or_404(Possibility, pk=possibility_id)
    if possibility.result != "Pending":
        raise Http404("Result is not pending")
    if request.method == 'POST':
        form = PossibilityResultForm(request.POST, instance=possibility)
        if form.is_valid():
            if possibility.result == "Win":
                bets = Bet.objects.filter(possibility=possibility)
                for bet in bets:
                    user = bet.username
                    user.points += possibility.quotation * bet.putting
                    user.save()
            form.save()
    else:
        form = PossibilityResultForm(instance=possibility)

    return render(request, "minamax/change_result.html", {"form": form, "possibility": possibility, "possibility_id": possibility.id})
    return LoginView.as_view(template_name="minamax/login.html")(
        request, *args, **kwargs
    )


@login_required
def to_bet(request):
    if request.method == "POST":
        form = BetForm(request.POST)
        if form.is_valid():
            bet = form.save(commit=False)
            bet.username = request.user
            user = bet.username
            user.points += -bet.putting
            bet.save()
            user.save()
            return redirect("../")
    else:
        form = BetForm()

    return render(request, "minamax/to_bet.html", {"form": form})

minamaxdjango/minamax/templates/events/index.html
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No events are available.</p>
{% endif %}

minamaxdjango/minamax/templates/login.html
{% block content %}
<h2>Connexion</h2>
<form method="post" action="{% url 'login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Connexion</button>
</form>
{% endblock %}

minamaxdjango/minamax/templates/minamax/base.html
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}MINAMAX - Paris Sportifs{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'minamax/style.css' %}">
</head>

<body>

    <header>
        <a href="{% url 'minamax:index' %}">
            <img src="{% static 'minamax/logo.svg' %}" alt="Logo_MINAMAX">
        </a>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>Bonjour, {{ user.username }} ({{ user.points }} points)</li>
                <li><a href="{% url 'minamax:profile' %}">Profil</a></li>
                {% else %}
                <li><a href="{% url 'minamax:login' %}">Se Connecter</a></li>
                <li><a href="{% url 'minamax:signup' %}">Créer un Compte</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}{% endblock %}
    </main>

    <footer>
        <p>&copy; 2024 MINAMAX - Tous droits réservés.</p>
    </footer>

</body>

</html>

minamaxdjango/minamax/templates/minamax/change_result.html
<h2>Modifier le résultat de la possibilite {{ possibility.description_text }} de l'evenement {{ possibility.event }}
</h2>
<form method="post" action="{% url 'minamax:change_result' possibility_id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Enregistrer les modifications</button>
</form>

minamaxdjango/minamax/templates/minamax/detail.html
{% extends "minamax/base.html" %}
{% block header %}MINAMAX{% endblock %}
{% block content %}
<h1>Name of event: {{ event.event_text }}</h1>
<h2>Date: {{ event.event_date }}</h2>


<ul>
    <h3> Liste des possibilitées:</h3>
    {% for possibility in possibilities_list %}
    <li>{{ possibility.description_text }} => cote de {{ possibility.quotation }} </li>
    <a href="{% url 'minamax:to_bet'%}">
        <button>Parier</button>
    </a>
    {% endfor %}
</ul>
{% endblock %}

minamaxdjango/minamax/templates/minamax/index.html
{% extends "minamax/base.html" %}
{% block header %}MINAMAX{% endblock %}
{% block content %}


<ul>
    <h1> Liste des évènements:</h1>
    {% for event in latest_event_list %}
    <li><a href="{% url 'minamax:detail' event.id %}">{{ event.event_text }}</a></li>
    {% endfor %}
</ul>


{% endblock %}

minamaxdjango/minamax/templates/minamax/login.html
{% extends "minamax/base.html" %}
{% block header %}MINAMAX{% endblock %}
{% block content %}
<h2>Connexion</h2>
<form method="post" action="{% url 'minamax:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Connexion</button>
</form>
{% endblock %}

minamaxdjango/minamax/templates/minamax/profile.html
{% extends "minamax/base.html" %}
{% block header %}MINAMAX{% endblock %}
{% block content %}
<h2>Profil de {{ user.username }}</h2>
<p>Adresse email: {{ user.email }}</p>
<p>Points: {{ user.points }}</p>
{% endblock %}

minamaxdjango/minamax/templates/minamax/signup.html
{% extends "minamax/base.html" %}
{% block header %}MINAMAX{% endblock %}
{% block content %}
<h2>Créer un compte</h2>
<form method="post" action="{% url 'minamax:signup' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">S'inscrire</button>
</form>
{% endblock %}

minamaxdjango/minamax/templates/minamax/to_bet.html
{% extends "minamax/base.html" %}
{% block header %}MINAMAX{% endblock %}
{% block content %}
<form method="post" action="{% url 'minamax:to_bet' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Bet</button>
</form>
{% endblock %}

minamaxdjango/minamax/templates/signup.html
{% block content %}
<h2>Créer un compte</h2>
<form method="post" action="{% url 'signup' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">S'inscrire</button>
</form>
{% endblock %}